name: metpy-workshop
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy==0.19.0.post1
  - jupyterlab==3.1.9
  - matplotlib==3.4.3
  - metpy==1.1.0
  - numpy==1.21.2
  - pykdtree==1.3.4
  - siphon==0.9